using QuectelController.Communication.CommandParameters;
using System;
using System.Collections.Generic;
using System.Text;

namespace QuectelController.Communication.Commands.General
{
    public class SetResponseFormattingCharacter : CommandBase
    {
        public override bool CanExecute => false;

        public override bool CanTest => false;

        public override bool CanRead => true;

        public override bool CanWrite => true;

        public override string Name => "Set Response Formatting Character";

        public override string Description => 
            @"This command determines the character generated by TA for result code and information text, along with 
the command line termination character set via ATS3.";

        public override CommandCategory Category => CommandCategory.GeneralCommands;

        public override IReadOnlyList<ICommandParameter> AvailableParameters => new[]
        {
            new IntegerCommandParameter ("n","Integer type. Response formatting character. Range: 0–127. Default: 10.",false)
        };

        protected override string RawCommand => "ATS4";
    }
}
